local o = vim.opt

o.clipboard = "unnamedplus" -- allows neovim to access the system clipboard
o.cmdheight = 2 -- more space in the neovim command line for displaying messages
o.completeopt = { "menuone", "noselect" } -- mostly just for cmp
o.conceallevel = 0 -- so that `` is visible in markdown files
o.fileencoding = "utf-8" -- the encoding written to a file
o.hlsearch = false -- highlight all matches on previous search pattern
o.ignorecase = true -- ignore case in search patterns
o.smartcase = true -- smart case
o.mouse = "a" -- allow the mouse to be used in neovim
o.pumheight = 5 -- pop up menu height
o.showmode = false -- we don't need to see things like -- INSERT -- anymore
o.showtabline = 2 -- always show tabs
o.smartindent = true -- make indenting smarter again
o.splitbelow = true -- force all horizontal splits to go below current window
o.splitright = true -- force all vertical splits to go to the right of current window
o.termguicolors = true -- set term gui colors (most terminals support this)
o.timeoutlen = 220 -- time to wait for a mapped sequence to complete (in milliseconds)
o.updatetime = 300 -- faster completion (4000ms default)
o.expandtab = true -- convert tabs to spaces
o.tabstop = 4 -- insert 4 spaces for a tab
o.shiftwidth = 4 -- the number of spaces inserted for each indentation
o.shiftround = true
o.cursorcolumn = true -- highlight the current line
o.cursorline = true -- highlight the current line
o.cursorlineopt = "number"
o.number = true -- set numbered lines
o.relativenumber = true -- set relative numbered lines
o.numberwidth = 4 -- set number column width to 2 {default 4}
o.signcolumn = "yes:1" -- always show the sign column otherwise it would shift the text each time
o.wrap = false -- display lines as one long line
o.scrolloff = 4 -- is one of my fav
o.background = "dark" -- or "light" for light mode
o.sidescrolloff = 8
o.colorcolumn = "80"
o.backup = false
o.writebackup = false -- if a file is being edited by another program (or was written to file while editing with another program) it is not allowed to be edited
o.swapfile = false
o.undofile = true
o.undodir = os.getenv("HOME") .. "/.nvimundo/"
-- new stuff below
o.inccommand = "split"
o.foldmethod = "indent"
o.foldlevel = 4
o.autoindent = true
o.copyindent = true
o.breakindent = true
o.spell = true
o.spelllang = "en_au"
